# Generated by Django 2.1.5 on 2019-02-21 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20190210_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='start_value',
        ),
    ]
