# Generated by Django 2.1.5 on 2019-02-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auction_start_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, default='auction_images/default/default.png', upload_to='auction_images/'),
        ),
    ]
