# Generated by Django 2.1.5 on 2019-02-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20190224_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='desc',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
