# Generated by Django 2.1.5 on 2019-02-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20190224_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='final_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
